from __future__ import annotations

from datetime import UTC, datetime
from uuid import uuid4

from .config import Settings

A2A_PROTOCOL_VERSION = "1.0"


def agent_card(settings: Settings, base_url: str = "") -> dict:
    url = base_url.rstrip("/") if base_url else ""
    interface_url = f"{url}/a2a/rpc" if url else "/a2a/rpc"
    return {
        "name": "Chat Orchestrate",
        "description": (
            "Distributed local-agent harness for coordinating Codex, Claude Code, Gemini CLI, "
            "OpenSwarm, and simulated agents across project workspaces."
        ),
        "supportedInterfaces": [
            {
                "url": interface_url,
                "protocolBinding": "JSONRPC",
                "protocolVersion": A2A_PROTOCOL_VERSION,
            }
        ],
        "provider": {
            "organization": "Chat Orchestrate local cluster",
            "url": url or "http://localhost",
        },
        "version": "0.1.0",
        "documentationUrl": "https://github.com/Rikhil-6/Chat-Orchestrate",
        "capabilities": {
            "streaming": False,
            "pushNotifications": False,
            "extendedAgentCard": True,
        },
        "securitySchemes": {
            "coordinationBearer": {
                "httpAuthSecurityScheme": {
                    "scheme": "Bearer",
                    "bearerFormat": "coordination-token",
                    "description": "Use the shared coordination token generated by the host.",
                }
            }
        },
        "securityRequirements": [{"coordinationBearer": []}] if settings.coordination_token else [],
        "defaultInputModes": ["text/plain", "application/json"],
        "defaultOutputModes": ["text/plain", "application/json"],
        "skills": [
            {
                "id": "project-orchestration",
                "name": "Project Orchestration",
                "description": "Breaks project goals into machine-routed agent tasks and tracks their outputs.",
                "tags": ["coordinator", "delegation", "project", "workspace"],
                "examples": [
                    "Build the backend on this machine and delegate frontend work to another machine.",
                    "Review the repo changes and summarize merge risks.",
                ],
            },
            {
                "id": "local-agent-handoff",
                "name": "Local Agent Handoff",
                "description": "Routes tasks to locally installed agent backends such as Codex or Claude Code.",
                "tags": ["codex", "claude-code", "gemini-cli", "openswarm", "local-agent"],
                "examples": [
                    "Ask the Codex worker to implement the API route.",
                    "Ask the Claude Code worker to review the frontend branch.",
                ],
            },
        ],
    }


def task_to_a2a(task: dict) -> dict:
    task_id = task.get("task_id") or task.get("id") or uuid4().hex
    status = _task_state(task.get("status", "delegated"))
    updated_at = task.get("updated_at") or task.get("created_at") or datetime.now(UTC).isoformat()
    goal = task.get("goal", "")
    result = task.get("result", "")
    history = [
        {
            "messageId": f"{task_id}-request",
            "taskId": task_id,
            "role": "ROLE_USER",
            "parts": [{"text": goal}],
            "metadata": {
                "project": task.get("project", "default"),
                "role": task.get("role", "coordinator"),
                "assignedMachine": task.get("assigned_machine", ""),
                "preferredBackend": task.get("preferred_backend", ""),
            },
        }
    ]
    if result:
        history.append(
            {
                "messageId": f"{task_id}-result",
                "taskId": task_id,
                "role": "ROLE_AGENT",
                "parts": [{"text": result}],
            }
        )
    return {
        "id": task_id,
        "contextId": task.get("run_id") or task.get("contextId") or "chat-orchestrate",
        "status": {
            "state": status,
            "timestamp": updated_at,
            "message": {
                "messageId": f"{task_id}-status",
                "taskId": task_id,
                "role": "ROLE_AGENT",
                "parts": [{"text": task.get("title") or status}],
            },
        },
        "history": history,
        "artifacts": _artifacts(task),
        "metadata": {
            "chatOrchestrateTaskId": task_id,
            "project": task.get("project", "default"),
            "role": task.get("role", "coordinator"),
            "assignedMachine": task.get("assigned_machine", ""),
            "preferredBackend": task.get("preferred_backend", ""),
        },
    }


def create_task_from_send_message(state: dict, params: dict, default_machine: str = "") -> dict:
    message = params.get("message", {})
    metadata = params.get("metadata", {})
    task_id = uuid4().hex
    now = datetime.now(UTC).isoformat()
    role = metadata.get("role") or "coordinator"
    goal = _message_text(message).strip() or metadata.get("goal") or "A2A delegated task"
    task = {
        "task_id": task_id,
        "run_id": message.get("contextId") or uuid4().hex,
        "project": metadata.get("project") or "default",
        "goal": goal,
        "role": role,
        "title": metadata.get("title") or f"{role.title()} pass: {goal[:80]}",
        "assigned_machine": metadata.get("assignedMachine") or default_machine,
        "preferred_backend": metadata.get("preferredBackend") or "auto",
        "status": "delegated",
        "created_at": now,
        "updated_at": now,
        "result": "",
        "a2a": {
            "message": message,
            "configuration": params.get("configuration", {}),
            "metadata": metadata,
        },
    }
    state.setdefault("tasks", []).append(task)
    return task


def _message_text(message: dict) -> str:
    parts = message.get("parts") or []
    chunks = []
    for part in parts:
        if "text" in part:
            chunks.append(str(part["text"]))
        elif "data" in part:
            chunks.append(str(part["data"]))
    return "\n".join(chunks)


def _artifacts(task: dict) -> list[dict]:
    result = task.get("result", "")
    if not result:
        return []
    return [
        {
            "artifactId": f"{task.get('task_id', 'task')}-result",
            "name": "Agent result",
            "description": "Result returned by the assigned Chat Orchestrate worker.",
            "parts": [{"text": result, "mediaType": "text/plain"}],
        }
    ]


def _task_state(status: str) -> str:
    return {
        "delegated": "TASK_STATE_SUBMITTED",
        "running": "TASK_STATE_WORKING",
        "completed": "TASK_STATE_COMPLETED",
        "failed": "TASK_STATE_FAILED",
        "cancelled": "TASK_STATE_CANCELED",
        "canceled": "TASK_STATE_CANCELED",
    }.get(status, "TASK_STATE_UNSPECIFIED")
